steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'
      - '.'

  # Step 2: Push Docker Image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'

  # Step 3: Deploy the Docker Image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project $PROJECT_ID
        kubectl set image deployment/my-app-deployment my-app=gcr.io/$PROJECT_ID/my-app:$SHORT_SHA --namespace=default

images:
  - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'
